"""A starter question bank for the core syllabus modules.

The agent pipeline generates current-affairs questions from articles, but it
cannot invent an analogy or a figure series -- those come from the syllabus, not
from the news. Without them the seeded mock tests reference modules with an
empty bank and cannot assemble a paper, so the feature exists but does not work.

These are sample questions an operator is expected to grow or replace. Keyed by
module slug; every one is filed under that module for each service.
"""

from __future__ import annotations

# (stem, [options], correct_key, explanation, difficulty)
Question = tuple[str, list[str], str, str, str]

STARTER_QUESTIONS: dict[str, list[Question]] = {
    "verbal-intelligence": [
        ("Doctor is to Hospital as Teacher is to:",
         ["Student", "School", "Book", "Lesson"], "b",
         "The first term works in the place named by the second.", "easy"),
        ("Which word does not belong with the others?",
         ["Rifle", "Pistol", "Sword", "Carbine"], "c",
         "The others are firearms; a sword is a bladed weapon.", "easy"),
        ("Complete the series: 3, 6, 11, 18, 27, ?",
         ["36", "38", "39", "40"], "b",
         "The differences increase by two each time: 3, 5, 7, 9, 11.", "medium"),
        ("If FRIEND is coded as HTKGPF, how is CANDLE coded?",
         ["ECPFNG", "DBOEMF", "EDRFNG", "ECPFMG"], "a",
         "Each letter moves forward two places in the alphabet.", "medium"),
        ("Choose the word most nearly opposite in meaning to CANDID:",
         ["Frank", "Evasive", "Honest", "Blunt"], "b",
         "Candid means open and truthful; evasive is its opposite.", "easy"),
        ("Pointing to a man, Ali said, 'He is the son of my grandfather's only son.' "
         "How is the man related to Ali?",
         ["Uncle", "Brother", "Cousin", "Nephew"], "b",
         "The grandfather's only son is Ali's father, so the man is Ali's brother.", "medium"),
        ("A man walks 3 km north, turns right and walks 4 km. How far is he from the start?",
         ["5 km", "7 km", "4 km", "6 km"], "a",
         "A 3-4-5 right triangle: the straight-line distance is 5 km.", "medium"),
        ("Choose the word most nearly similar in meaning to DILIGENT:",
         ["Lazy", "Careless", "Industrious", "Hasty"], "c",
         "Diligent means hard-working and careful.", "easy"),
        ("All soldiers are brave. Some brave people are officers. Therefore:",
         ["All officers are soldiers", "Some soldiers may be officers",
          "No soldier is an officer", "All brave people are soldiers"], "b",
         "Only a possibility follows; the premises do not establish more.", "hard"),
        ("Complete the series: AZ, BY, CX, ?",
         ["DV", "DW", "EW", "DX"], "b",
         "The first letter advances while the second moves back.", "medium"),
    ],
    "non-verbal-intelligence": [
        ("A figure is rotated 90 degrees clockwise. A shape pointing north now points:",
         ["South", "East", "West", "North"], "b",
         "A quarter turn clockwise from north is east.", "easy"),
        ("In a mirror placed to the right, the word LEVEL appears as:",
         ["LEVEL", "LEVEL reversed", "LAVEL", "VELEL"], "b",
         "A mirror reverses left and right, so the letter order reverses.", "easy"),
        ("A square is folded twice and one corner is cut. When unfolded there will be:",
         ["1 hole", "2 holes", "4 holes", "8 holes"], "c",
         "Two folds make four layers, so one cut produces four holes.", "medium"),
        ("A series shows 1, 2, 3 then 4 dots added each step. The fifth figure has:",
         ["9 dots", "13 dots", "17 dots", "21 dots"], "c",
         "1, 5, 9, 13, 17 -- four are added at each step.", "medium"),
        ("Which is the odd figure: three shapes with four sides and one with three?",
         ["First", "Second", "Third", "Fourth"], "d",
         "The odd figure is the one whose side count differs.", "easy"),
        ("A cube painted on all faces is cut into 27 equal cubes. How many have exactly "
         "three painted faces?",
         ["4", "6", "8", "12"], "c",
         "The eight corner cubes each show three painted faces.", "hard"),
    ],
    "academic-english": [
        ("Choose the correct sentence:",
         ["He do not know the answer.", "He does not knows the answer.",
          "He does not know the answer.", "He not know the answer."], "c",
         "After 'does not' the verb stays in its base form.", "easy"),
        ("Fill in the blank: She has been living here ______ 2015.",
         ["for", "since", "from", "by"], "b",
         "'Since' marks a point in time; 'for' marks a duration.", "easy"),
        ("Choose the word closest in meaning to METICULOUS:",
         ["Careless", "Thorough", "Rapid", "Reluctant"], "b",
         "Meticulous means showing great attention to detail.", "medium"),
        ("Identify the error: 'Neither of the candidates were selected.'",
         ["Neither", "of the candidates", "were", "selected"], "c",
         "'Neither' is singular, so the verb should be 'was'.", "medium"),
        ("Choose the correct preposition: The soldier was accused ______ negligence.",
         ["for", "with", "of", "on"], "c",
         "One is accused *of* something.", "easy"),
        ("What is the passive form of 'The officer briefed the men'?",
         ["The men were briefed by the officer.", "The men are briefed by the officer.",
          "The men had briefed the officer.", "The officer was briefed by the men."], "a",
         "Past simple active becomes 'were' plus the past participle.", "medium"),
        ("Choose the correctly spelled word:",
         ["Occurence", "Occurrence", "Ocurrence", "Occurrance"], "b",
         "Occurrence has two Cs and two Rs.", "easy"),
        ("'To take the bull by the horns' means to:",
         ["Avoid a problem", "Face a difficulty directly",
          "Work with animals", "Act without thinking"], "b",
         "The idiom means to confront a difficulty head on.", "medium"),
    ],
}

STARTER_QUESTIONS.update({
    "mathematics": [
        ("A candidate scores 45 out of 60. What percentage is that?",
         ["70%", "75%", "80%", "85%"], "b",
         "45/60 = 0.75.", "easy"),
        ("If 3x + 7 = 22, what is x?",
         ["3", "5", "7", "15"], "b",
         "3x = 15, so x = 5.", "easy"),
        ("The average of 5 numbers is 18. Their total is:",
         ["72", "80", "90", "95"], "c",
         "Average times count: 18 x 5 = 90.", "easy"),
        ("A rectangle is 12 m by 8 m. Its perimeter is:",
         ["20 m", "40 m", "48 m", "96 m"], "b",
         "Perimeter = 2(12 + 8) = 40 m.", "easy"),
        ("A train covers 180 km in 3 hours. Its average speed is:",
         ["45 km/h", "50 km/h", "60 km/h", "90 km/h"], "c",
         "180 / 3 = 60 km/h.", "easy"),
        ("The area of a circle of radius 7 cm (using pi = 22/7) is:",
         ["154 sq cm", "144 sq cm", "168 sq cm", "196 sq cm"], "a",
         "Area = pi r squared = 22/7 x 49 = 154.", "medium"),
        ("A shopkeeper buys for 800 and sells for 920. The profit percentage is:",
         ["12%", "15%", "18%", "20%"], "b",
         "Profit 120 on 800 is 15%.", "medium"),
        ("If sin(theta) = 3/5, then cos(theta) is:",
         ["4/5", "3/4", "5/4", "5/3"], "a",
         "A 3-4-5 triangle: cos = adjacent/hypotenuse = 4/5.", "medium"),
    ],
    "physics": [
        ("The SI unit of force is the:",
         ["Joule", "Newton", "Watt", "Pascal"], "b",
         "Force is measured in newtons.", "easy"),
        ("A body at rest stays at rest unless acted on by a force. This is:",
         ["Newton's first law", "Newton's second law",
          "Newton's third law", "The law of gravitation"], "a",
         "The first law is the law of inertia.", "easy"),
        ("The speed of light in a vacuum is approximately:",
         ["3 x 10^6 m/s", "3 x 10^8 m/s", "3 x 10^10 m/s", "3 x 10^5 m/s"], "b",
         "About 300,000 km per second.", "easy"),
        ("Ohm's law states that voltage equals:",
         ["Current divided by resistance", "Current times resistance",
          "Resistance divided by current", "Power times current"], "b",
         "V = IR.", "easy"),
        ("Light bending as it passes from air into water is called:",
         ["Reflection", "Refraction", "Diffraction", "Dispersion"], "b",
         "Refraction is the change of direction at a boundary.", "medium"),
    ],
    "general-knowledge": [
        ("The Pakistan Military Academy is located at:",
         ["Risalpur", "Kakul", "Quetta", "Mangla"], "b",
         "PMA is at Kakul, near Abbottabad.", "easy"),
        ("Pakistan gained independence on:",
         ["14 August 1947", "23 March 1940", "15 August 1947", "6 September 1965"], "a",
         "14 August 1947.", "easy"),
        ("The highest gallantry award in Pakistan is the:",
         ["Sitara-e-Jurat", "Tamgha-e-Jurat", "Nishan-e-Haider", "Hilal-e-Jurat"], "c",
         "Nishan-e-Haider is the highest military award.", "easy"),
        ("Defence Day is observed in Pakistan on:",
         ["23 March", "14 August", "6 September", "25 December"], "c",
         "6 September marks the 1965 war.", "easy"),
        ("The Pakistan Air Force Academy is at:",
         ["Kakul", "Risalpur", "Karachi", "Sargodha"], "b",
         "The PAF Academy is at Risalpur.", "easy"),
        ("K2, the world's second highest mountain, lies in the:",
         ["Hindu Kush", "Himalayas", "Karakoram", "Sulaiman Range"], "c",
         "K2 is in the Karakoram range.", "medium"),
        ("The headquarters of the United Nations is in:",
         ["Geneva", "New York", "Vienna", "Paris"], "b",
         "The UN Secretariat is in New York.", "easy"),
        ("Pakistan's naval headquarters is located in:",
         ["Karachi", "Islamabad", "Gwadar", "Ormara"], "b",
         "Naval Headquarters is in Islamabad; Karachi is the main base.", "medium"),
    ],
    "islamiat": [
        ("How many pillars of Islam are there?",
         ["Three", "Four", "Five", "Six"], "c",
         "Shahadah, Salah, Zakat, Sawm and Hajj.", "easy"),
        ("The first revelation came to the Prophet (PBUH) in the cave of:",
         ["Thawr", "Hira", "Uhud", "Safa"], "b",
         "In the cave of Hira, near Makkah.", "easy"),
        ("The migration from Makkah to Madinah is known as the:",
         ["Hajj", "Hijrah", "Isra", "Fath"], "b",
         "The Hijrah marks the start of the Islamic calendar.", "easy"),
        ("How many surahs are there in the Holy Quran?",
         ["110", "112", "114", "116"], "c",
         "There are 114 surahs.", "easy"),
    ],
})
